In [1]:
import tarfile
import glob
import gzip
import pandas as pd
import numpy as np

In [4]:
tar = tarfile.open('GSE73357_RAW.tar')
tar.extractall(path='raw')
tar.close()

In [16]:

tars = glob.glob('raw/*.gz')
for i,fname in enumerate(tars):
    #print(i)
    with gzip.open(fname, "rb") as f:
        data=f.read()
    with open(fname[:-3],'w') as f:
        f.write(data.decode('utf-8'))

In [2]:
rpl10a = glob.glob('raw/*Rpl10a-Ribo*.txt')
ribos = glob.glob('raw/*Ribo*.txt')
ribos

['raw\\GSM1891620_Total-Ribo-Seq_for_Rpl10a_1.txt',
 'raw\\GSM1891621_Total-Ribo-Seq_for_Rpl10a_2.txt',
 'raw\\GSM1891622_Rpl10a-Ribo-Seq_1.txt',
 'raw\\GSM1891623_Rpl10a-Ribo-Seq_2.txt',
 'raw\\GSM1891624_Total-Ribo-Seq_for_Rps25_1.txt',
 'raw\\GSM1891625_Total-Ribo-Seq_for_Rps25_2.txt',
 'raw\\GSM1891626_Rps25-Ribo-Seq_1.txt',
 'raw\\GSM1891627_Rps25-Ribo-Seq_2.txt',
 'raw\\GSM2579679_Total-Ribo-Seq_for_Rpl22_1.txt',
 'raw\\GSM2579680_Total-Ribo-Seq_for_Rpl22_2.txt',
 'raw\\GSM2579681_Rpl22-Ribo-Seq_1.txt',
 'raw\\GSM2579682_Rpl22-Ribo-Seq_2.txt']

In [3]:
collate = pd.DataFrame()
collate['UCSC_ID'] = pd.read_csv(ribos[0],sep='\t')['UCSC_ID']
for idx,f in enumerate(ribos):
    df = pd.read_csv(f,sep='\t')
    group = f[15:-4]
    assert((df.columns == ['UCSC_ID','RPKM']).all())
    df.columns = ['UCSC_ID',group]
    collate = collate.merge(df, how='outer')

In [4]:
collate

,UCSC_ID,Total-Ribo-Seq_for_Rpl10a_1,Total-Ribo-Seq_for_Rpl10a_2,Rpl10a-Ribo-Seq_1,Rpl10a-Ribo-Seq_2,Total-Ribo-Seq_for_Rps25_1,Total-Ribo-Seq_for_Rps25_2,Rps25-Ribo-Seq_1,Rps25-Ribo-Seq_2,Total-Ribo-Seq_for_Rpl22_1,Total-Ribo-Seq_for_Rpl22_2,Rpl22-Ribo-Seq_1,Rpl22-Ribo-Seq_2
0,uc009avm.1,0.2,0.1,9.6,2.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,uc012gyf.1,0.2,0.8,7.3,14.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,uc033hyx.1,0.7,0.1,12.2,2.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,uc007wrm.2,0.5,0.3,2.0,10.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,uc008emr.1,0.7,0.7,4.2,8.7,2.9,2.4,6.1,6.5,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9493,uc009azc.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.1,5.1,8.2,8.3
9494,uc007qgz.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.1,3.1,4.1,6.0
9495,uc007all.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.4,3.5,5.6,5.0
9496,uc008yng.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,4.3,6.5,11.0
9497,uc009uhj.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.1,0.0,10.0,1.0

In [83]:
collate_filter10 = collate.loc[(collate[collate.columns[1:]]>=10).all(1),:]
collate_filter10

,UCSC_ID,Total-Ribo-Seq_for_Rpl10a_1,Total-Ribo-Seq_for_Rpl10a_2,Rpl10a-Ribo-Seq_1,Rpl10a-Ribo-Seq_2,Total-Ribo-Seq_for_Rps25_1,Total-Ribo-Seq_for_Rps25_2,Rps25-Ribo-Seq_1,Rps25-Ribo-Seq_2,Total-Ribo-Seq_for_Rpl22_1,Total-Ribo-Seq_for_Rpl22_2,Rpl22-Ribo-Seq_1,Rpl22-Ribo-Seq_2
25,uc009dsm.2,24.5,33.2,116.7,128.6,41.5,37.2,126.9,103.8,712.1,654.3,916.6,778.8
28,uc009jsd.1,19.4,19.9,74.8,86.0,21.9,23.0,39.2,27.3,82.8,108.8,129.7,117.2
31,uc007hnk.2,429.5,951.0,2861.1,2727.6,1970.0,1101.6,3434.3,2664.4,15356.1,15950.8,18756.8,22739.7
65,uc009qsi.1,41.5,54.1,144.9,135.3,48.8,45.3,97.7,90.4,73.9,79.8,82.8,66.1
83,uc007pwj.1,23.9,23.7,53.2,75.0,29.1,29.4,50.7,36.5,58.1,58.5,75.8,54.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8414,uc009nad.2,10.1,12.7,22.5,20.6,12.4,14.3,20.9,15.3,17.6,12.5,13.1,10.4
8429,uc008xtw.1,16.2,12.6,37.5,17.8,15.7,14.7,21.5,21.5,17.2,15.8,21.7,18.7
8464,uc008dne.1,10.1,27.8,27.0,53.9,20.6,16.7,46.9,22.6,42.8,32.7,42.6,31.6
8465,uc012dag.1,10.9,22.9,34.9,38.2,33.6,31.1,35.5,55.0,23.9,20.6,23.1,14.2
8468,uc007kjt.1,14.6,20.8,24.7,51.7,19.6,19.5,20.1,31.5,33.6,27.7,27.7,30.4

In [82]:
collate_filter10.to_csv('collate_rpkms.csv',index=False)

In [6]:
collate.fillna(0).to_csv('collate_rpkms_noFil.csv',index=False)

In [7]:
results = glob.glob('deseq/res*.csv')
results

['deseq\\res_rpl10.csv', 'deseq\\res_rpl22.csv', 'deseq\\res_rpl25.csv']

In [8]:
for result in results:
    resdf = pd.read_csv(result)
    genes = list(resdf.loc[(resdf['log2FoldChange']<-0.64) & (resdf['padj']<0.05),'Unnamed: 0'])
    with open(result.split('\\')[1]+'_dep', 'w') as f:
        for item in genes:
            f.write("%s\n" % item)

In [6]:
with open('bg.txt', 'w') as f:
    for item in list(collate['UCSC_ID']):
        f.write("%s\n" % item)